mysql:
  host: "192.168.31.31"
  port: 33054
  user: "bat_smart_sopt"
  password: "P@ssw0rd"
  database: "db_bat_tja1"

  # host: "192.168.40.44"
  # port: 3306
  # user: "root"
  # password: "P@ssw0rd"
  # database: "db_bat_tja1"